DenyUsers freezeprotect
Match User freezeprotect-commission Address *,!192.168.111.0/24,!192.168.114.0/24
    DenyUsers freezeprotect-commission
Match all
Match User freezeprotect-commission Address 192.168.111.0/24,192.168.114.0/24
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    ForceCommand /usr/local/lib/freeze-protect-commission/ssh-dispatch
    AllowTcpForwarding no
    AllowStreamLocalForwarding no
    AllowAgentForwarding no
    X11Forwarding no
    PermitTunnel no
    PermitTTY no
    GatewayPorts no
    PermitUserRC no
Match all
